### ISSUE TITLE
Usage 3.1 is problematic

### ISSUE THREAD

**Issue by tkotani** [giovannipizzi/seekpath#10]
Honestly speaking, Usage 3.1 is very problematic,
It is convenient if you can add the rotation matrix connecting the user-provided cell
and the conventional cell, as an output of get_path.

**Comment by giovannipizzi** [comment]
Indeed, I imagined this would be the case, but before I didn't have the time to work on this. 
I started a test implementation in the following branch: https://github.com/giovannipizzi/seekpath/tree/fix_transformation_matrix
It's still not complete (not implemented for the triclinic case) and only partially tested (but I already added some test cases).

Now ``get_path`` returns a new key ``conv_transformation_matrix``. The explanation is in the readme: https://github.com/giovannipizzi/seekpath/tree/fix_transformation_matrix#33transformation-matrix.

Could you test it for some cases (but not for triclinic yet, that I still need to implement), and see if you see any bug or any problem?

**Comment by tkotani** [comment]
Dear giovannipizzi,
I am sorry for late reply. I had a cold and duties to finalize this semester...
I myself  solved this problem.
I did it by the matching procedure of inner product-matrices of "reciprocal_primitive_lattice" and that of the linear combinations of given primitive lattice.
