### ISSUE TITLE
Provide Transformation Matrix as output of the code

### ISSUE THREAD

**Issue by giovannipizzi** [giovannipizzi/seekpath#16]
This is being worked in branch fix_transformation_matrix

**Comment by giovannipizzi** [comment]
Missing things:
- implement triclinic
- check that tests work check the conventional matrix
- add also trasform to conventional?

**Comment by tkotani** [comment]
It is nice if seekpath can find the transformation matrix.

FYI
In mathematics, a set of the three vectors which defines a lattice is called as the Z-basis. Two Z-basis, which defines the same lattice, is connected by an unimodular matrix.
General theory of unimodular matrix is too difficult for me. So I wrote a simple code to find the unimodular matrix for my purpose. But it is helpful if you include a code in seekpath.

**Comment by iorin0217** [comment]
I think the "transformation_matrix" has not sufficient information about converting the input structure to the seekpath output conventional structure, and the "std_rotation_matrix" is needed.
Do you agree with me?

**Comment by giovannipizzi** [comment]
Some notes from the TODO.txt file that I will remove from the repo:

- If possible, it would be nice to have the transformation matrix. 
  NOTE: this is being worked in the branch 'fix_transformation_matrix'.
   a. for non-aP lattices, this should be already possible. 
   Check if it is sufficient to combine the transf_matrix with the P matrix 
   b. for aP lattices, we should probably check if we can get the matrix out 
      of Niggli-reduce. This should be easy to obtain. Then,
  dd to the output:
    - the transformation matrix from user to standard, and from standard to 
      primitive (and the combination)
    - a warning/flag to say if the cell has changed in the process 
      (probably it will almost always change?)

**Comment by giovannipizzi** [comment]
Thanks @jaemolihm - I merged #97 now, this should indirectly also address this issue that I will therefore close (I also deleted my own old branch)
