### ISSUE TITLE
link orientation of reciprocal and real space

### ISSUE THREAD

**Issue by ltalirz** [giovannipizzi/seekpath#46]
While real and reciprocal lattices are, of course, different, *orientation* in real and reciprocal space has the same meaning.

Finding a way to indicate the correspondence between real-space and reciprocal-space directions can be very helpful for linking properties like dispersion of bands, etc.  to the crystal structure.

In the seekpath output you show both real and reciprocal space side by side, and you could couple the two orientations together (so that, if you rotate one, the other rotates accordingly).

**Comment by giovannipizzi** [comment]
Good point. However, now the two visualisers are implemented completely independently and it's non-obvious. As I plan to change visualiser for the structure anyway, I might wait until then and then check how hard it is to do.

**Comment by giovannipizzi** [comment]
Moving to [tools-seekpath](https://github.com/materialscloud-org/tools-seekpath) repository, and closing here
