### ISSUE TITLE
any plan for jupyter/jupyterlab plugin?

### ISSUE THREAD

**Issue by specter119** [giovannipizzi/seekpath#47]
It seems that the python package can only generate he K path, and the visualization functions is outside the python package? 

seekpath must be the best k-path visualization tool I have ever met, and the rotatable can add into jupyter/jupyterlab, it will be more helpful.

Thanks in advance.

**Comment by giovannipizzi** [comment]
Hi, sorry for replying only now. 
Indeed, currently the visualiser is implemented in JS. 
I've never worked on a proper Jupyter plugin using JS code, but it seems like a good idea. If you have any suggestion on how to do it, stub of code, or even a PR, please let me know.

**Comment by giovannipizzi** [comment]
Moving to [tools-seekpath](https://github.com/materialscloud-org/tools-seekpath) repository, and closing here
