### ISSUE TITLE
highlight suggested path more

### ISSUE THREAD

**Issue by ltalirz** [giovannipizzi/seekpath#55]
this is a suggestion by andrea ferretti - he mentions that when using seekpath in class, (some) students end up using the "high symmetry points" as the path and don't read to the very bottom where it provides the actual suggested path.

One could even think of putting the suggested path before the coordinates of the corresponding labels.

**Comment by giovannipizzi** [comment]
Good point. I'm happy to discuss more and then do the changes (we're also migrating the web part of the tool to tools-barebone so we might do this change at the same time)
