### ISSUE TITLE
Seekpath failed to pass this example: https://aiida-tutorials.readthedocs.io/en/latest/_downloads/41fc098a6347cd8d1653a71b79cc51eb/launch_auto-wannier_workflow.py

### ISSUE THREAD

**Issue by hongyi-zhao** [giovannipizzi/seekpath#82]
See [here](https://github.com/aiidateam/aiida-sssp/issues/3#issuecomment-612397057) for detail.

**Comment by giovannipizzi** [comment]
This does not seem related to seekpath but to how a wrapper library is called, closing

**Comment by hongyi-zhao** [comment]
Fixed it, see [here](https://github.com/aiidateam/aiida-wannier90-workflows/pull/4).
