### ISSUE TITLE
Finding the kpath for interface, say, heterojunction, by seekpath.

### ISSUE THREAD

**Issue by hongyi-zhao** [giovannipizzi/seekpath#93]
Hi,

Can I use seekpath to find the kpath for interface, say, heterojunction?

Regards,
HY

**Comment by giovannipizzi** [comment]
Hi,
you can, but seekpath assumes 3D periodic boundary conditions.
So probably
1. you will get some lines with only 1-2 points, along the directions that correspond to very large unit cell vector lengths in real space
2. the code will use symmetries - if your interface loses most of them, you will get a very "trivial" path, in the worst case the one for triclinic cells
